# TCL File Generated by Component Editor 21.1
# Wed Mar 25 14:56:10 EDT 2026
# DO NOT MODIFY


# 
# vga_ball "VGA Ball" v1.0
#  2026.03.25.14:56:10
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module vga_ball
# 
set_module_property DESCRIPTION ""
set_module_property NAME vga_ball
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "VGA Ball"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_assignment embeddedsw.dts.vendor "csee4840"
set_module_assignment embeddedsw.dts.name "vga_ball"
set_module_assignment embeddedsw.dts.group "vga"
# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL vga_ball
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file vga_ball.sv SYSTEM_VERILOG PATH vga_ball.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter BALL_RADIUS STD_LOGIC_VECTOR 20
set_parameter_property BALL_RADIUS DEFAULT_VALUE 20
set_parameter_property BALL_RADIUS DISPLAY_NAME BALL_RADIUS
set_parameter_property BALL_RADIUS WIDTH 12
set_parameter_property BALL_RADIUS TYPE STD_LOGIC_VECTOR
set_parameter_property BALL_RADIUS UNITS None
set_parameter_property BALL_RADIUS ALLOWED_RANGES 0:4095
set_parameter_property BALL_RADIUS HDL_PARAMETER true
add_parameter BALL_R STD_LOGIC_VECTOR 255
set_parameter_property BALL_R DEFAULT_VALUE 255
set_parameter_property BALL_R DISPLAY_NAME BALL_R
set_parameter_property BALL_R WIDTH 9
set_parameter_property BALL_R TYPE STD_LOGIC_VECTOR
set_parameter_property BALL_R UNITS None
set_parameter_property BALL_R ALLOWED_RANGES 0:511
set_parameter_property BALL_R HDL_PARAMETER true
add_parameter BALL_G STD_LOGIC_VECTOR 255
set_parameter_property BALL_G DEFAULT_VALUE 255
set_parameter_property BALL_G DISPLAY_NAME BALL_G
set_parameter_property BALL_G WIDTH 9
set_parameter_property BALL_G TYPE STD_LOGIC_VECTOR
set_parameter_property BALL_G UNITS None
set_parameter_property BALL_G ALLOWED_RANGES 0:511
set_parameter_property BALL_G HDL_PARAMETER true
add_parameter BALL_B STD_LOGIC_VECTOR 255
set_parameter_property BALL_B DEFAULT_VALUE 255
set_parameter_property BALL_B DISPLAY_NAME BALL_B
set_parameter_property BALL_B WIDTH 9
set_parameter_property BALL_B TYPE STD_LOGIC_VECTOR
set_parameter_property BALL_B UNITS None
set_parameter_property BALL_B ALLOWED_RANGES 0:511
set_parameter_property BALL_B HDL_PARAMETER true
add_parameter BG_R STD_LOGIC_VECTOR 0
set_parameter_property BG_R DEFAULT_VALUE 0
set_parameter_property BG_R DISPLAY_NAME BG_R
set_parameter_property BG_R WIDTH 9
set_parameter_property BG_R TYPE STD_LOGIC_VECTOR
set_parameter_property BG_R UNITS None
set_parameter_property BG_R ALLOWED_RANGES 0:511
set_parameter_property BG_R HDL_PARAMETER true
add_parameter BG_G STD_LOGIC_VECTOR 0
set_parameter_property BG_G DEFAULT_VALUE 0
set_parameter_property BG_G DISPLAY_NAME BG_G
set_parameter_property BG_G WIDTH 9
set_parameter_property BG_G TYPE STD_LOGIC_VECTOR
set_parameter_property BG_G UNITS None
set_parameter_property BG_G ALLOWED_RANGES 0:511
set_parameter_property BG_G HDL_PARAMETER true
add_parameter BG_B STD_LOGIC_VECTOR 128
set_parameter_property BG_B DEFAULT_VALUE 128
set_parameter_property BG_B DISPLAY_NAME BG_B
set_parameter_property BG_B WIDTH 9
set_parameter_property BG_B TYPE STD_LOGIC_VECTOR
set_parameter_property BG_B UNITS None
set_parameter_property BG_B ALLOWED_RANGES 0:511
set_parameter_property BG_B HDL_PARAMETER true


# 
# module assignments
# 
set_module_assignment embeddedsw.dts.group vga
set_module_assignment embeddedsw.dts.name vga_ball
set_module_assignment embeddedsw.dts.vendor csee4840


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 writedata writedata Input 16
add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 chipselect chipselect Input 1
add_interface_port avalon_slave_0 address address Input 3
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point vga
# 
add_interface vga conduit end
set_interface_property vga associatedClock clock
set_interface_property vga associatedReset ""
set_interface_property vga ENABLED true
set_interface_property vga EXPORT_OF ""
set_interface_property vga PORT_NAME_MAP ""
set_interface_property vga CMSIS_SVD_VARIABLES ""
set_interface_property vga SVD_ADDRESS_GROUP ""

add_interface_port vga VGA_B b Output 8
add_interface_port vga VGA_BLANK_n blank_n Output 1
add_interface_port vga VGA_CLK clk Output 1
add_interface_port vga VGA_G g Output 8
add_interface_port vga VGA_HS hs Output 1
add_interface_port vga VGA_R r Output 8
add_interface_port vga VGA_SYNC_n sync_n Output 1
add_interface_port vga VGA_VS vs Output 1

